apiVersion: v1
kind: Service
metadata:
  namespace: backend
  name: backend-svc
spec:
  type: LoadBalancer
  selector:
    app: angular-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080